"""empty message

Revision ID: bf5c2f3e2cae
Revises: 
Create Date: 2018-03-18 17:21:20.077375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5c2f3e2cae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('team_code', sa.String(length=5), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('conference', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('team_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
